modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
license="MIT"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
credits="Screem, Julian++, Gecko"
authors="quek"
description='''Deep underground, a forgotten land awaits.'''
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4]"
    ordering="NONE"
    side="BOTH"
