modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
credits="Screem: music and some textures"
authors="quek"
description='''Deep underground, a forgotten land awaits.'''
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
