modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits=""
authors="quek"
description='''
ill do this later
'''
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
