modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
credits="Screem: music, some sounds & art; Gecko: made the old biome provider"
authors="quek"
description='''Deep underground, a forgotten land awaits.'''
license="MIT"
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
