modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
license="MIT"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
description='''
Developer and Creator: Quek
Artists: Screem, Frenderman, Echolite

Deep underground, a forgotten land awaits.'''
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.5]"
    ordering="NONE"
    side="BOTH"
